# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c0962e8654eaea03dc2fea3c7149df1aba4a99a74fde4496ff6e6778475eec3eed85d7e94aa805ab9e6374eadc3183ea7829322767bed2839a717dad60e3920

test:
  secret_key_base: 367c0a0f1d72270324d39f672c280b446845734c67fe19bd580e9c8d75659e26a78e5d3dca0dfbdecefc00e42534a9f0c4edb705100931d48f6472c810f8e49d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
